In [15]:
import numpy as np

In [2]:
x = [5, 7, -2, 2]
y = [4, 5, 12, 0]

In [4]:
product = []
for i in range(len(x)):
    product.append(x[i] * y[i])
product 

[20, 35, -24, 0]

In [5]:
#same result if we multiply arrays
np.array(x) * np.array(y)

array([ 20,  35, -24,   0])

In [8]:
A = np.array([[1, 2], [2,1]])
B = np.array([[1, 5], [0, 2]])

In [9]:
A + 5 * B

array([[ 6, 27],
       [ 2, 11]])

In [14]:
#matrix multiplication is via np.dot
np.dot(A, B)

array([[ 1,  9],
       [ 2, 12]])

In [16]:
a = np.array([[0], [7]])
b = np.array([[1, 2], [0, 6]])
c = np.array([[2, 2]])

In [17]:
a.shape

(2, 1)

In [18]:
b.shape

(2, 2)

In [19]:
c.shape

(1, 2)

In [21]:
a + c

array([[2, 2],
       [9, 9]])

linalg module in numpy

In [23]:
A = np.array([[3, 4], [2, 3]])

In [24]:
A

array([[3, 4],
       [2, 3]])

In [27]:
A.T #transpose matrix A (rows are now columns)

array([[3, 2],
       [4, 3]])

In [28]:
#compute inverse of A

np.linalg.inv(A)

array([[ 3., -4.],
       [-2.,  3.]])

In [30]:
np.dot(A, np.linalg.inv(A)) #confirming inverse correctly multiplies together to get identity matrix

array([[1., 0.],
       [0., 1.]])

In [32]:
#check rank of matrix

np.linalg.matrix_rank(A)

2

In [33]:
#test same functino on matrix that doesnt have full rank

B = np.array([[1, 0], [0, 0]])

In [35]:
np.linalg.inv(B)  #returns error as singular matrix

LinAlgError: Singular matrix

In [36]:
np.linalg.matrix_rank(B)

1

In [37]:
# solving Ax = b

b = np.array([[1], [2]])

In [38]:
x = np.linalg.solve(A, b)
x

array([[-5.],
       [ 4.]])

In [39]:
np.dot(A, x)   #prove

array([[1.],
       [2.]])

In [59]:
# exercise

A = np.array([[2, 1, 1], [-5, -3, 0], [1, 1, -1]])

In [60]:
A

array([[ 2,  1,  1],
       [-5, -3,  0],
       [ 1,  1, -1]])

In [61]:
b = np.array([[-1], [1], [-2]])

In [46]:
b

array([[-1],
       [ 1],
       [-2]])

In [47]:
np.linalg.matrix_rank(A)

3

In [62]:
np.linalg.inv(A)

array([[-3., -2., -3.],
       [ 5.,  3.,  5.],
       [ 2.,  1.,  1.]])

In [63]:
np.dot(np.linalg.inv(A), b)

array([[  7.],
       [-12.],
       [ -3.]])

In [64]:
x = np.linalg.solve(A, b)
x

array([[  7.],
       [-12.],
       [ -3.]])

adding a new line 

In [65]:
A = np.array([[2, 1, 1], [-5, -3, 0], [1, 1, -1], [0, 5, -1]])

In [66]:
A

array([[ 2,  1,  1],
       [-5, -3,  0],
       [ 1,  1, -1],
       [ 0,  5, -1]])

In [54]:
b = b = np.array([[-1], [1], [-2], [1]])

In [55]:
b

array([[-1],
       [ 1],
       [-2],
       [ 1]])

In [67]:
np.linalg.solve(A, b)    #doesnt work as now matrix is no longer square so therefore no inverse

LinAlgError: Last 2 dimensions of the array must be square