In [49]:
import numpy as np

In [4]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
#check dimensions of an array with .ndim
a1.ndim

1

In [7]:
a1.shape

(3,)

In [9]:
#create two dimensional array
a2 = np.array([[1, 2, 3], [3, 4, 5]])
a2

array([[1, 2, 3],
       [3, 4, 5]])

In [11]:
a2.ndim
#axis is the amount of inner lists

2

In [13]:
a2.shape

(2, 3)

for a 2d numpy array first axis corresponds to down direction (rows) and second to the across (columns)
so intuitively axis=0 is rows and axis=1 is columns

In [17]:
#if multiple data types np.array will use most general.. specify type if required ie
a3 = np.array([1, 2, 3.3], dtype=int)
a3
#3.3 has been rounded down to an integer (from float) as a result

array([1, 2, 3])

In [18]:
a4 = np.array([["f", "l", "a", "k", "e"], ["s", "n", "a", "k", "e"], ["a", "w", "a", "k", "e"]])
a4.shape

(3, 5)

In [20]:
np.arange(0, 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.arange(0, 15, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [22]:
#use np.linspace() if want to specify the number of points
np.linspace(0, 100, 3)

array([  0.,  50., 100.])

In [25]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
a.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
#reshape to a 3D shape!
a.reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [30]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [31]:
A * B

array([[2, 0],
       [0, 4]])

In [33]:
#dot() for matrix multiplication
A.dot(B)

array([[5, 4],
       [3, 4]])

In [34]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5,6]])

In [37]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [42]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [45]:
a = np.reshape(np.arange(12), (4, 3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
#select subset of data
a[0, 0]

0

In [47]:
a[3, 0]

9

In [48]:
a[1:3, 0]

array([3, 6])

In [51]:
# colon selects all values
a[:, 2]

array([ 2,  5,  8, 11])

In [52]:
#select all elements from 0:4 in increments of 2
a[0:4:2, 0]

array([0, 6])

In [53]:
#modify view changes array
a[0, 0] = 5

In [54]:
a

array([[ 5,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [57]:
b = a[1:4]
b

array([2, 3, 4])

In [58]:
b[0] = 200
b

array([200,   3,   4])

In [60]:
a[1]

200

In [64]:
a = np.arange(1, 37)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [66]:
a = a.reshape(6, 6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [70]:
blue = a[:, 1]
blue

array([ 2,  8, 14, 20, 26, 32])

In [72]:
yellow = a[0:2, 4:6]
yellow

array([[ 5,  6],
       [11, 12]])

In [74]:
red = a[5, 4:6]
red

array([35, 36])

In [77]:
green = a[2:5:2, 0:5:2]
green

array([[13, 15, 17],
       [25, 27, 29]])

In [78]:
a = np.reshape(np.arange(12), (4, 3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
a > 8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [80]:
a[a>8]

array([ 9, 10, 11])

In [81]:
a[a>8] = 0
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 0, 0]])

this is called masking

In [82]:
a = np.reshape(np.arange(12), (4, 3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [89]:
a = np.array([1, 2, 3])
a * 10

array([10, 20, 30])

In [92]:
#broadcasting = stretching arrays to be same dimension
a = np.array([[1], [2], [3], [4,]])
b = np.array([10, 20, 30])
a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

both arrays a and b have been "stretched" to match shapes

In [1]:
dist_to_origin = [0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391]

In [37]:
#create numpy array of list
dist = np.array([dist_to_origin])

In [38]:
dist

array([[   0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391]])

In [39]:
dist_T = dist.reshape(10, 1)
dist_T

array([[   0],
       [1498],
       [1063],
       [1968],
       [1498],
       [1758],
       [1469],
       [1472],
       [2230],
       [2391]])

In [44]:
#distance is the absolute value of diff
dist_matrix = np.abs(dist-dist_T)
dist_matrix

array([[   0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1063,  435,    0,  905,  435,  695,  406,  409, 1167, 1328],
       [1968,  470,  905,    0,  470,  210,  499,  496,  262,  423],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1758,  260,  695,  210,  260,    0,  289,  286,  472,  633],
       [1469,   29,  406,  499,   29,  289,    0,    3,  761,  922],
       [1472,   26,  409,  496,   26,  286,    3,    0,  758,  919],
       [2230,  732, 1167,  262,  732,  472,  761,  758,    0,  161],
       [2391,  893, 1328,  423,  893,  633,  922,  919,  161,    0]])

if want to work on copy of original array use copy function

In [48]:
a = np.arange(12)
b = a.copy()[:2]
b[0] = 10
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
#reshaping
a = np.arange(12)
b = a.reshape(3, 4)
b[0] = 10
b

array([[10, 10, 10, 10],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
#a has changed too
a

array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9, 10, 11])